config/routes.rb
Rails.application.routes.draw do
  root 'calendars#index'
  resources :calendars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/plan.rb
class Plan < ApplicationRecord
  validates :plan, presence: true
  validates :date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController

  # カレンダー表示画面
  def index
    get_week
    @plan = Plan.new
  end

  # 予定の保存
  def create
    Plan.create(plan_params)
    redirect_to action: :index
  end

  private

  def plan_params
    params.require(:plan).permit(:date, :plan)
  end

  def get_week
    wdays = ['(日)','(月)','(火)','(水)','(木)','(金)','(土)']

    @todays_date = Date.today
    @week_days = []

    # 今週分の予定を一括取得
    plans = Plan.where(date: @todays_date..@todays_date + 6)

    7.times do |x|
      date = @todays_date + x
      today_plans = []

      # 該当日の予定を抽出
      plans.each do |plan|
        today_plans.push(plan.plan) if plan.date == date
      end

      # 曜日番号を取得（0〜6）
      wday_num = date.wday

      # 曜日を日本語に変換
      wday_str = wdays[wday_num]

      # 日付データを1日分ハッシュで格納
      days = {
        month: date.month,
        date: date.day,
        wday: wday_str,
        plans: today_plans
      }

      @week_days.push(days)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/index.html.erb
  <%= form_with model: @plan, url: calendars_path, class: 'form' do |f| %>
    <%= f.label :日付を選択, class: 'label' %>
    <%= f.date_field :date, class: 'date-select' %>
    <%= f.label :予定を入力, class: 'label' %>
    <%= f.text_field :plan, class: 'text-input' %>
    <%= f.submit '保存' %>
  <% end %>

  <div class='calendar'>
    <% @week_days.each do |day| %>
      <div class='item'>
        <div class='date'>
          <%= day[:month] %>/<%= day[:date] %> <%= day[:wday] %>
        </div>
        <ul class='content'>
        <% if day[:plans].length != 0 %>
          <% day[:plans].each do |plan| %>
            <li class='plan-list'>・<%= plan %></li>
          <% end %>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrainingCurriculumRails7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>